# License policy used by the release workflow against the exact Cargo.lock.
# The allowed set reflects the licenses currently present in the resolved
# dependency graph; additions require an explicit policy review.

[graph]
targets = [
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
]

[licenses]
confidence-threshold = 0.8
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "MIT",
    "Unicode-3.0",
    "Unlicense",
]
